default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: say_something_development
test:
  <<: *default
  database: say_something_test
production:
  <<: *default
  database: say_something_production
  username: say_something
  password: <%= ENV['SAY_SOMETHING_DATABASE_PASSWORD'] %>
